ALTER TABLE patient_profiles
  ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN DEFAULT FALSE;

ALTER TABLE doctor_profiles
  ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_listed BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS accepting_patients BOOLEAN DEFAULT TRUE;
