ALTER TABLE patient_profiles 
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS province VARCHAR(100);

ALTER TABLE doctor_profiles
ADD COLUMN IF NOT EXISTS hospital_affiliation VARCHAR(255),
ADD COLUMN IF NOT EXISTS practice_city VARCHAR(100),
ADD COLUMN IF NOT EXISTS practice_province VARCHAR(100);
